---
- name: Testing out conditional statement
  hosts: linux
  become: yes
  tasks:
    - name: Install multiple packages on Ubuntu
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - htop
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install multiple packages on RHEL
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - htop
      when: ansible_facts['os_family'] == 'RedHat'

