---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

# - name: Install Docker Compose (if configured).
  # get_url:
    # url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    # dest: "{{ docker_compose_path }}"
    # mode: 0755

- name: Copy docker-compose dependencies.
  copy:
    src: "{{ item }}"
    dest: "/tmp/dependency/"
  with_fileglob: "{{ docker_compose_rpm_file_path }}/dependency/*.rpm"
  
## TODO Pre rpm installation
- name: Install all the docker-compose dependencies.
  shell: "rpm -ivh --force /tmp/dependency/{{ item }}"
  ignore_errors: true
  with_items:
    - "mpfr-3.1.1-4.el7.x86_64.rpm"
    - "libmpc-1.0.1-3.el7.x86_64.rpm"
    - "cpp-4.8.5-39.el7.x86_64.rpm"
    - "kernel-headers-3.10.0-1062.4.1.el7.x86_64.rpm"
    - "glibc-headers-2.17-292.el7.x86_64.rpm"
    - "glibc-devel-2.17-292.el7.x86_64.rpm"
    - "keyutils-libs-devel-1.5.8-3.el7.x86_64.rpm"
    - "libverto-devel-0.2.5-4.el7.x86_64.rpm"
    - "libsepol-devel-2.5-10.el7.x86_64.rpm"
    - "pcre-devel-8.32-17.el7.x86_64.rpm"
    - "libselinux-devel-2.5-14.1.el7.x86_64.rpm"
    - "libcom_err-devel-1.42.9-16.el7.x86_64.rpm"
    - "libkadm5-1.15.1-37.el7_7.2.x86_64.rpm"
    - "krb5-libs-1.15.1-37.el7_6.x86_64.rpm"
    - "krb5-devel-1.15.1-37.el7_7.2.x86_64.rpm"
    - "zlib-devel-1.2.7-18.el7.x86_64.rpm"
    - "bzip2-devel-1.0.6-13.el7.x86_64.rpm"
    - "gcc-4.8.5-39.el7.x86_64.rpm"
    - "openssl-devel-1.0.2k-19.el7.x86_64.rpm"
    - "sqlite-3.7.17-8.el7.x86_64.rpm"
    - "sqlite-devel-3.7.17-8.el7.x86_64.rpm"
    - "libtirpc-0.2.4-0.16.el7.x86_64.rpm"
  
- name: Copy python dependencies.
  copy:
    src: "{{ item }}"
    dest: "/tmp/python/"
  with_fileglob: "{{ docker_compose_rpm_file_path }}/python/*.rpm"

# Install python dependencies at one go.
- name: Install Python dependency at once.
  shell: "rpm -ivh --force /tmp/python/python3-3.6.8-10.el7.x86_64.rpm /tmp/python/python3-pip-9.0.3-5.el7.noarch.rpm /tmp/python/python3-setuptools-39.2.0-10.el7.noarch.rpm /tmp/python/python3-libs-3.6.8-10.el7.x86_64.rpm"
  ignore_errors: true

## TODO install Python rpms
- name: Install all the python dependencies.
  shell: "rpm -ivh --force /tmp/python/{{ item }}"
  ignore_errors: true
  with_items:
    - "python36-six-1.11.0-3.el7.noarch.rpm"
    - "python36-dockerpty-0.4.1-10.el7.noarch.rpm"
    - "libyaml-0.1.4-11.el7_0.x86_64.rpm"
    - "python36-PyYAML-3.12-1.el7.x86_64.rpm"
    - "python36-chardet-3.0.4-1.el7.noarch.rpm"
    - "python36-pysocks-1.6.8-6.el7.noarch.rpm"
    - "python36-cached_property-1.5.1-2.el7.noarch.rpm"
    - "python36-jsonschema-2.5.1-4.el7.noarch.rpm"
    - "python36-websocket-client-0.47.0-2.el7.noarch.rpm"
    - "python36-idna-2.7-2.el7.noarch.rpm"
    - "python36-urllib3-1.19.1-5.el7.noarch.rpm"
    - "python36-docopt-0.6.2-8.el7.noarch.rpm"
    - "python36-texttable-1.6.2-1.el7.noarch.rpm"
    - "python36-docker-pycreds-0.2.1-2.el7.noarch.rpm"
    - "python36-requests-2.12.5-3.el7.noarch.rpm"
    - "python36-docker-2.6.1-3.el7.noarch.rpm"

- name: Copy Docker-compose rpms.
  copy:
    src: "{{ item }}"
    dest: "/tmp/docker_compose/"
  with_fileglob: "{{ docker_compose_rpm_file_path }}/{{ docker_compose_version }}.rpm"

## TODO install docker compose rpm
- name: Install docker-compose.
  shell: "rpm -ivh --force /tmp/docker_compose/docker-compose-1.18.0-4.el7.noarch.rpm"
  ignore_errors: true


# - name: Install all the docker-compose dependencies and docker.
  # command: "rpm -ivh --force {{ item }}"
  # ignore_errors: true
  # with_items:
      # - "/tmp/docker/"
      # - "/tmp/docker/"
      # - "/tmp/docker/"
